import { chromium } from "playwright-core"
const out = "/tmp/claude-0/-home-user/7824a982-3b74-50e1-abe5-6bb120608676/scratchpad/forms-agent"
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" })
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
await page.addInitScript(() => localStorage.setItem("tecton-docs:theme", "light"))
await page.goto(`http://localhost:4437/docs/components/field`, { waitUntil: "networkidle" })
const ex = page.locator("[data-example=field-validation] [data-slot=preview]")
await ex.scrollIntoViewIfNeeded()
await ex.locator("tec-button").click()
await page.waitForTimeout(400)
await ex.screenshot({ path: `${out}/int-field-validation.png` })
await page.goto(`http://localhost:4437/docs/components/input-otp`, { waitUntil: "networkidle" })
const otp = page.locator("[data-example=input-otp-separator] [data-slot=preview]")
await otp.scrollIntoViewIfNeeded()
await otp.locator("tec-input-otp-slot").first().click({ force: true })
await page.keyboard.type("123")
await page.waitForTimeout(300)
await otp.screenshot({ path: `${out}/int-otp.png` })
await browser.close()
