import { chromium } from "playwright-core"
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" })
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
const errs = []
p.on("pageerror", (e) => errs.push(e.message))
await p.goto("http://localhost:4437/docs/components/questionnaire", { waitUntil: "networkidle" })
await p.waitForTimeout(2000)
const v = p.locator("#questionnaire-validation")
await v.locator('tec-questionnaire-choice[value="summary"]').click()
await v.locator("tec-questionnaire-next").click()
await p.waitForTimeout(300)
await v.locator('tec-questionnaire-choice[value="public"]').click()
await v.locator("tec-questionnaire-submit").click()
await p.waitForTimeout(500)
console.log("validation item:", await v.locator("tec-questionnaire").evaluate((q) => q.item), await v.locator('tec-questionnaire-item[name="detail"] tec-questionnaire-error').evaluate((e) => e.matches(":state(invalid)") + " " + e.textContent))
const d = p.locator("#questionnaire-dialog")
await d.locator('tec-button[slot="trigger"]').click()
await p.waitForTimeout(500)
await d.locator('tec-questionnaire-choice[value="feature"]').click()
await p.keyboard.press("Enter")
await p.waitForTimeout(300)
await p.keyboard.press("2")
await p.waitForTimeout(100)
console.log("dialog item:", await d.locator("tec-questionnaire").evaluate((q) => q.item))
await p.keyboard.press("Enter")
await p.waitForTimeout(600)
console.log("dialog result:", await d.locator("[data-result]").textContent(), await d.locator("tec-dialog").evaluate((x) => x.open))
const n = p.locator("#questionnaire-navigation-state")
console.log("nav next disabled:", await n.locator("tec-questionnaire-next").evaluate((x) => x.disabled))
await n.locator('tec-questionnaire-choice[value="files"]').click()
await p.waitForTimeout(200)
console.log("nav next disabled after answer:", await n.locator("tec-questionnaire-next").evaluate((x) => x.disabled))
const c = p.locator("#questionnaire-conditional")
await c.locator('tec-questionnaire-choice[value="cloud"]').click()
await p.waitForTimeout(200)
console.log("progress:", await c.locator("tec-questionnaire-progress").evaluate((x) => x.shadowRoot.textContent.trim()))
console.log("errors:", errs)
await b.close()
