// GENERATED by scripts/build-index.mjs from src/components/*/define.ts — do not edit.
/**
 * `import "@tecton/wc"` registers every Tecton element and exports every element class.
 * Import `@tecton/wc/<family>` instead to register one family (smaller bundles).
 */
export * from "./components/background/define.js"
export * from "./components/button/define.js"
export * from "./components/chart/define.js"
export * from "./components/checkbox/define.js"
export * from "./components/icon/define.js"
export * from "./components/popover/define.js"
export * from "./components/tabs/define.js"
export * from "./icons/index.js"
