#!/usr/bin/env node
/**
 * Generates the files derived from the folder structure, so adding a component never requires
 * editing a shared file:
 *
 *   src/index.ts             `@tecton/wc`: imports every `src/components/<family>/define.ts`
 *                            (registering the family) and re-exports its classes.
 *   src/autoloader-map.ts    tag → loader of the family that owns the tag (for `@tecton/wc/autoloader`).
 *   src/styles/cloak.css     `@tecton/wc/cloak.css`: hides undefined tec-* elements until they upgrade.
 *
 * A tag belongs to the family whose define.ts registers it with a class from its own folder
 * (families also register the families they render, e.g. copy-button registers tec-button).
 *
 * Usage: node scripts/build-index.mjs [--check]
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const componentsDir = join(root, "src/components")
const families = readdirSync(componentsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(componentsDir, d.name, "define.ts")))
  .map((d) => d.name)
  .sort()

// ---------------------------------------------------------------- tag ownership
const owner = new Map() // tag → family
const fallback = new Map()
for (const family of families) {
  const source = readFileSync(join(componentsDir, family, "define.ts"), "utf8")
  const local = new Set()
  for (const m of source.matchAll(/import\s*\{([^}]*)\}\s*from\s*["'](\.[^"']*)["']/g)) {
    if (!m[2].startsWith("./")) continue
    for (const name of m[1].split(",")) local.add(name.trim().split(/\s+as\s+/).pop())
  }
  for (const m of source.matchAll(/defineElement\(\s*["'](tec-[a-z0-9-]+)["']\s*,\s*(\w+)/g)) {
    const [, tag, cls] = m
    if (local.has(cls) && !owner.has(tag)) owner.set(tag, family)
    if (!fallback.has(tag)) fallback.set(tag, family)
  }
}
for (const [tag, family] of fallback) if (!owner.has(tag)) owner.set(tag, family)
const tags = [...owner.keys()].sort()

// ---------------------------------------------------------------- outputs
const index = `// GENERATED by scripts/build-index.mjs from src/components/*/define.ts — do not edit.
/**
 * \`import "@tecton/wc"\` registers every Tecton element and exports every element class.
 * Import \`@tecton/wc/<family>\` instead to register one family (smaller bundles), or
 * \`@tecton/wc/autoloader\` to register families on demand as their tags appear.
 */
${families.map((f) => `export * from "./components/${f}/define.js"`).join("\n")}
export * from "./icons/index.js"
`

const map = `// GENERATED by scripts/build-index.mjs from src/components/*/define.ts — do not edit.
/** Every Tecton tag → the loader of the family that registers it (${tags.length} tags, ${families.length} families). */
export const loaders: Record<string, () => Promise<unknown>> = {
${families
  .map((f) => {
    const own = tags.filter((t) => owner.get(t) === f)
    if (!own.length) return null
    const load = `() => import("./components/${f}/define.js")`
    return own.map((t) => `  "${t}": ${load},`).join("\n")
  })
  .filter(Boolean)
  .join("\n")}
}
`

const selector = tags.map((t) => `${t}:not(:defined)`).join(",\n")
const cloak = `/* GENERATED by scripts/build-index.mjs — do not edit.
 * Optional: hides Tecton elements until their definition loads, so the page never shows raw,
 * unstyled light-DOM content (a flash of undefined custom elements). If a definition never
 * arrives (a failed script, a family that was not imported), the content is revealed after
 * --tec-cloak-timeout (2s) anyway, so nothing can stay hidden for good.
 *   @import "@tecton/wc/cloak.css";   or   <link rel="stylesheet" href=".../cloak.css">
 */
@keyframes tec-cloak-reveal {
  to {
    visibility: visible;
  }
}
${selector} {
  visibility: hidden;
  animation: tec-cloak-reveal 0s var(--tec-cloak-timeout, 2s) forwards;
}
`

const outputs = {
  "src/index.ts": index,
  "src/autoloader-map.ts": map,
  "src/styles/cloak.css": cloak,
}
if (process.argv.includes("--check")) {
  let stale = 0
  for (const [file, content] of Object.entries(outputs)) {
    const target = join(root, file)
    if (!existsSync(target) || readFileSync(target, "utf8") !== content) {
      console.error(`stale: ${file} (run node scripts/build-index.mjs)`)
      stale++
    }
  }
  if (stale) process.exit(1)
  console.log("index, autoloader map and cloak up to date")
} else {
  for (const [file, content] of Object.entries(outputs)) writeFileSync(join(root, file), content)
  console.log(`src/index.ts: ${families.length} families; autoloader map + cloak.css: ${tags.length} tags`)
}
