#!/usr/bin/env node
/**
 * Builds the Tecton web component theme from the Tecton token export in tokens/
 * (raw tokens, colour ramps and the semantic mapping; replace those files with a newer export).
 *
 *   src/styles/tokens.css    raw Tecton tokens (--tecton-*), light + dark      (verbatim)
 *   src/styles/palette.css   Tecton colour ramps (--tecton-palette-*)          (verbatim, minus the Tailwind @theme block)
 *   src/styles/theme.css     semantic layer (--tec-*), the public theming API of every component
 *   src/styles/tecton.css    the one file applications import: tokens + palette + theme + base
 *   src/styles/tailwind.css  optional Tailwind v4 preset: maps the theme onto Tailwind's namespaces
 *                            so an application's own light DOM can use bg-primary, text-muted-foreground,
 *                            rounded-md, bg-blue-120 … with the same values the components use.
 *
 * Usage: node scripts/build-theme.mjs [--check]
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const vendor = (f) => readFileSync(join(root, "tokens", f), "utf8")
const check = process.argv.includes("--check")
const HEADER = (src) =>
  `/* GENERATED by scripts/build-theme.mjs from tokens/${src} — do not edit */\n`

/** Returns the body of every top-level `selector { … }` block (non-nested). */
function blocks(css) {
  const out = []
  const re = /(^|\n)([^\n{}@/][^{}]*?)\{([^{}]*)\}/g
  let m
  while ((m = re.exec(css))) out.push({ selector: m[2].trim(), body: m[3] })
  return out
}

function decls(body) {
  return [...body.matchAll(/^\s*(--[\w-]+)\s*:\s*([^;]+);/gm)].map((m) => [m[1], m[2].trim()])
}

// ---------------------------------------------------------------- tokens / palette
const tokensCss = vendor("tecton-tokens.css")
const paletteCss = vendor("tecton-palette.css").replace(/@theme inline \{[\s\S]*\}\s*$/, "")

// ---------------------------------------------------------------- semantic theme
const themeSrc = vendor("tecton-theme.css")
const themeBlocks = blocks(themeSrc.replace(/@theme inline \{[\s\S]*\}\s*$/, ""))
const themeInline = decls(themeSrc.match(/@theme inline \{([\s\S]*)\}\s*$/)[1])

const semanticNames = new Set()
const rename = (value) =>
  value.replace(/var\(--([\w-]+)/g, (all, name) =>
    name.startsWith("tecton-") ? all : `var(--tec-${name}`
  )

let theme = HEADER("tecton-theme.css")
theme += `/*
 * The semantic layer. Every component reads only these --tec-* variables (and the
 * raw --tecton-* tokens / --tecton-palette-* ramps they point at). Custom properties
 * inherit through shadow roots, so re-pointing one of them on any ancestor re-themes
 * every component below it; data-theme="dark" | "light" (or .dark / .light) switches mode.
 */\n`
const selectorMap = {
  ":root": ":root",
  ".dark": '.dark, [data-theme="dark"]',
  '.light, [data-theme="light"]': '.light, [data-theme="light"]',
}
for (const { selector, body } of themeBlocks) {
  const sel = selectorMap[selector] ?? selector
  theme += `\n${sel} {\n`
  for (const [name, value] of decls(body)) {
    const n = `--tec-${name.slice(2)}`
    semanticNames.add(n)
    theme += `  ${n}: ${rename(value)};\n`
  }
  theme += "}\n"
}

// Fonts, radii and the few Tailwind theme values the components are specified in.
const extras = {
  "--tec-font-sans": "var(--tecton-font-family-sans), ui-sans-serif, system-ui, sans-serif",
  "--tec-font-mono": "var(--tecton-font-family-mono), ui-monospace, monospace",
}
for (const [name, value] of themeInline) {
  const m = name.match(/^--radius-(\w+)$/)
  if (m) extras[`--tec-radius-${m[1]}`] = value
}
Object.assign(extras, {
  "--tec-radius-3xl": "calc(var(--tec-radius) * 2.2)",
  "--tec-radius-4xl": "calc(var(--tec-radius) * 2.6)",
  // Tailwind v4 type scale (font-size / line-height) the component specs use.
  "--tec-text-xs": "0.75rem",
  "--tec-text-xs--line-height": "calc(1 / 0.75)",
  "--tec-text-sm": "0.875rem",
  "--tec-text-sm--line-height": "calc(1.25 / 0.875)",
  "--tec-text-base": "1rem",
  "--tec-text-base--line-height": "calc(1.5 / 1)",
  "--tec-text-lg": "1.125rem",
  "--tec-text-lg--line-height": "calc(1.75 / 1.125)",
  "--tec-text-xl": "1.25rem",
  "--tec-text-xl--line-height": "calc(1.75 / 1.25)",
  "--tec-text-2xl": "1.5rem",
  "--tec-text-2xl--line-height": "calc(2 / 1.5)",
  "--tec-font-weight-normal": "400",
  "--tec-font-weight-medium": "500",
  "--tec-font-weight-semibold": "600",
  // Tailwind v4 shadows.
  "--tec-shadow-xs": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  "--tec-shadow-sm": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
  "--tec-shadow-md": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  "--tec-shadow-lg": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
  "--tec-shadow-xl": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
  // Motion.
  "--tec-duration-fast": "100ms",
  "--tec-duration": "150ms",
  "--tec-duration-slow": "200ms",
  "--tec-ease": "cubic-bezier(0.4, 0, 0.2, 1)",
  "--tec-ease-out": "cubic-bezier(0, 0, 0.2, 1)",
  // Focus ring (Tailwind ring-2 ring-ring) and the invalid ring.
  "--tec-focus-ring": "0 0 0 2px var(--tec-ring)",
  "--tec-focus-ring-invalid": "0 0 0 2px color-mix(in oklab, var(--tec-destructive) 20%, transparent)",
  // Layering for non-top-layer overlays (sticky headers, sidebars).
  "--tec-z-sticky": "10",
  "--tec-z-overlay": "50",
})
theme += "\n:root {\n"
for (const [n, v] of Object.entries(extras)) {
  semanticNames.add(n)
  theme += `  ${n}: ${v};\n`
}
theme += "}\n"

// Dark mode tweaks that Tailwind expressed with dark: variants in the component classes.
theme += `
.dark, [data-theme="dark"] {
  --tec-focus-ring-invalid: 0 0 0 2px color-mix(in oklab, var(--tec-destructive) 40%, transparent);
}
.light, [data-theme="light"] {
  --tec-focus-ring-invalid: 0 0 0 2px color-mix(in oklab, var(--tec-destructive) 20%, transparent);
}
`

// ---------------------------------------------------------------- base + bundle
const base = `/*
 * Document-level base rules (optional, part of tecton.css). Components never rely on
 * them; they give the page the Tecton background, text colour and font.
 */
@layer tecton-base {
  :root {
    font-family: var(--tec-font-sans);
    background-color: var(--tec-background);
    color: var(--tec-foreground);
    -webkit-font-smoothing: antialiased;
  }
  * {
    scrollbar-width: thin;
    scrollbar-color: var(--tec-border) transparent;
  }
}
`

const bundle =
  `/* GENERATED by scripts/build-theme.mjs — do not edit.\n * Import once per document: @import "@tecton/wc/tecton.css" (or <link rel="stylesheet">). */\n` +
  `@import "./tokens.css";\n@import "./palette.css";\n@import "./theme.css";\n@import "./base.css";\n`

// ---------------------------------------------------------------- tailwind preset
const tw = []
for (const n of semanticNames) {
  const name = n.slice(6)
  if (name.startsWith("radius-")) tw.push(`  --${name}: var(${n});`)
  else if (name === "font-sans" || name === "font-mono") tw.push(`  --${name}: var(${n});`)
  else if (/^(text|shadow|duration|ease|z|focus|font-weight|radius$)/.test(name)) continue
  else tw.push(`  --color-${name}: var(${n});`)
}
const paletteNames = [...new Set([...paletteCss.matchAll(/--tecton-palette-([\w-]+)\s*:/g)].map((m) => m[1]))]
const tailwind = `/* GENERATED by scripts/build-theme.mjs — do not edit.
 * Optional Tailwind v4 preset for an application's own (light DOM) markup:
 *   @import "tailwindcss";
 *   @import "@tecton/wc/tailwind.css";
 * Components do not need it; they are styled inside their shadow roots.
 * The stock Tailwind palette is reset, so only Tecton colours exist (bg-blue-120, text-gray-830 …).
 */
@custom-variant dark (&:where(.dark *, [data-theme="dark"] *));
@theme inline {
  --color-*: initial;
${tw.join("\n")}
${paletteNames.map((p) => `  --color-${p}: var(--tecton-palette-${p});`).join("\n")}
}
/* Borders default to the theme's divider colour (a bare \`border\` class), as in Tecton. */
@layer base {
  *, ::before, ::after, ::backdrop, ::file-selector-button {
    border-color: var(--tec-border);
  }
}
`

// ---------------------------------------------------------------- write
const outputs = {
  "src/styles/tokens.css": HEADER("tecton-tokens.css") + tokensCss,
  "src/styles/palette.css": HEADER("tecton-palette.css") + paletteCss.replace(/^\/\* GENERATED[^\n]*\n/, "").trimEnd() + "\n",
  "src/styles/theme.css": theme,
  "src/styles/base.css": HEADER("(base rules)") + base,
  "src/styles/tecton.css": bundle,
  "src/styles/tailwind.css": tailwind,
}
let stale = 0
for (const [file, content] of Object.entries(outputs)) {
  const path = join(root, file)
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
      console.error(`stale: ${file}`)
      stale++
    }
  } else writeFileSync(path, content)
}
if (check && stale) process.exit(1)
console.log(check ? "theme up to date" : `wrote ${Object.keys(outputs).length} files, ${semanticNames.size} --tec-* variables`)
