#!/usr/bin/env node
/**
 * Generates src/index.ts — the `@tecton/wc` entry point — from the folder structure:
 * every `src/components/<family>/define.ts` is imported (registering the family) and re-exported
 * (each define.ts re-exports its classes). Adding a component never requires editing a shared file.
 *
 * Usage: node scripts/build-index.mjs [--check]
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const componentsDir = join(root, "src/components")
const families = readdirSync(componentsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(componentsDir, d.name, "define.ts")))
  .map((d) => d.name)
  .sort()

const content = `// GENERATED by scripts/build-index.mjs from src/components/*/define.ts — do not edit.
/**
 * \`import "@tecton/wc"\` registers every Tecton element and exports every element class.
 * Import \`@tecton/wc/<family>\` instead to register one family (smaller bundles).
 */
${families.map((f) => `export * from "./components/${f}/define.js"`).join("\n")}
export * from "./icons/index.js"
`

const target = join(root, "src/index.ts")
if (process.argv.includes("--check")) {
  if (!existsSync(target) || readFileSync(target, "utf8") !== content) {
    console.error("stale: src/index.ts (run node scripts/build-index.mjs)")
    process.exit(1)
  }
  console.log("src/index.ts up to date")
} else {
  writeFileSync(target, content)
  console.log(`src/index.ts: ${families.length} families`)
}
