/**
 * @module chart-cartesian
 * The cartesian kind: bar, line, area and scatter series (mixed freely, like a composed chart) on a
 * category (or number) axis and a value axis, with the grid, the axes, the cursor, reference
 * lines/areas/dots, error bars, value labels and the brush.
 *
 * Two navigation modes: by row (bars, lines, areas: the arrow keys move between categories, or
 * between the rows of a number axis) and, as soon as the chart has a `tec-chart-scatter`, by point
 * (every scatter point in x order).
 */
import { html, nothing, svg, type SVGTemplateResult } from "lit"
import { brushHeight, renderBrush, type BrushModel } from "./chart-brush.js"
import { entryColor, formatValue, type ChartRow } from "./chart-config.js"
import {
  avoidOverlaps,
  bubbleRadius,
  clampWindow,
  errorExtent,
  nearestIndex,
  nearestPoint,
  numericSlots,
  parseRange,
  placeBarLabel,
  placePointLabel,
  resolveDomain,
  smallestStep,
  symbolPath,
  brushPosition,
  type LabelBox,
  type LabelPlacement,
} from "./chart-cartesian-engine.js"
import {
  layoutReferences,
  referenceExtents,
  renderErrors,
  renderReferenceAreas,
  renderReferenceMarks,
  renderText,
  textAnchor,
  type CartesianFrame,
  type ErrorDraw,
  type ReferenceDraw,
  type TextDraw,
} from "./chart-cartesian-marks.js"
import { areaPath, barPositions, categoryAt, categoryScale, linePath, linearScale, roundedRect, thinTicks, type CategorySlot, type ChartCurve, type Point } from "./chart-engine.js"
import { numeric, type ChartContext, type ChartKind, type ChartModelBase, type Rect } from "./chart-kind.js"
import {
  TecChartArea,
  TecChartAxis,
  TecChartBar,
  TecChartBrush,
  TecChartErrorBar,
  TecChartGrid,
  TecChartLabelList,
  TecChartLine,
  TecChartScatter,
  TecChartXAxis,
  TecChartYAxis,
  TecChartZAxis,
  type ChartScatterShape,
} from "./chart-parts.js"

export interface SeriesSpec {
  kind: "bar" | "line" | "area" | "scatter"
  key: string
  /** The series element (absent for series generated by the `type` shortcut). */
  element?: Element
  color?: string
  stack?: string
  radius: [number, number, number, number]
  maxBarSize?: number
  curve: ChartCurve
  strokeWidth: number
  dots: boolean
  dashed: boolean
  fillOpacity: number
  gradient: boolean
  /** Scatter: the mark, and whether the points are connected. */
  shape?: ChartScatterShape
  line?: boolean
  nameKey?: string
  /** The value labels and error bars placed inside the series element. */
  labels?: TecChartLabelList[]
  errors?: TecChartErrorBar[]
}

/** A point of a scatter series. */
export interface ScatterMark extends Point {
  /** The navigation index (points are ordered by x, then series). */
  index: number
  /** The series (index into `model.series`) and the drawn row (index into `model.rows`). */
  series: number
  row: number
  r: number
  xValue: number
  yValue: number
  zValue: number | null
  d: string
}

export interface SeriesDraw {
  spec: SeriesSpec
  color: string
  bars: { index: number; d: string; fill: string; negative: boolean; x: number; y: number; w: number; h: number }[]
  /** Line/area points per category (null where the value is missing). */
  points: (Point | null)[]
  bases: (Point | null)[]
  /** Scatter points, in row order. */
  marks: ScatterMark[]
}

export interface CartesianModel extends ChartModelBase {
  kind: "cartesian"
  horizontal: boolean
  /** The drawn rows (the brush window; on a number axis, only the rows with a numeric position). */
  rows: ChartRow[]
  /** The index in the chart's `data` of every drawn row. */
  indexes: number[]
  /** Whether the category axis is a number axis. */
  numeric: boolean
  /** Point navigation: the chart has scatter series; `count` is the number of points. */
  scatter: boolean
  slots: CategorySlot[]
  hasBars: boolean
  series: SeriesDraw[]
  valueTicks: { value: number; pos: number }[]
  /** Maps a value to its position on the value axis. */
  scale: (value: number) => number
  valueDomain: [number, number]
  /** The number category axis. */
  baseTicks: { value: number; pos: number }[]
  baseScale?: (value: number) => number
  baseDomain?: [number, number]
  specs: SeriesSpec[]
  /** Scatter points in navigation order. */
  points: ScatterMark[]
  references: ReferenceDraw[]
  errors: ErrorDraw[]
  labels: TextDraw[]
  axisLabels: { x?: TextDraw; y?: TextDraw }
  brush?: BrushModel
}

export const TICK_SIZE = 6
/** Space between the x axis and the brush. */
const BRUSH_GAP = 8

function parseRadius(value: string | undefined): [number, number, number, number] {
  const parts = String(value ?? "0")
    .split(/[\s,]+/)
    .filter(Boolean)
    .map((v) => Number.parseFloat(v) || 0)
  if (parts.length >= 4) return [parts[0]!, parts[1]!, parts[2]!, parts[3]!]
  const r = parts[0] ?? 0
  return [r, r, r, r]
}

const xAxisOf = (ctx: ChartContext) => ctx.parts(TecChartXAxis)[0]
const yAxisOf = (ctx: ChartContext) => ctx.parts(TecChartYAxis)[0]

/** Whether the chart has a scatter series (point navigation, number axes on both sides). */
function isScatter(ctx: ChartContext): boolean {
  return ctx.parts(TecChartScatter).some((s) => s.key) || ctx.host.type === "scatter"
}

/** The data field of the categories: the chart's `category-key`, else the category axis' `key`. */
export function categoryKeyOf(ctx: ChartContext): string | undefined {
  if (ctx.host.categoryKey) return ctx.host.categoryKey
  const x = xAxisOf(ctx)?.key
  const y = yAxisOf(ctx)?.key
  return ctx.host.orientation === "horizontal" && !isScatter(ctx) ? (y ?? x) : (x ?? y)
}

const SHORTCUT_TYPES = new Set(["bar", "line", "area", "scatter"])

export function seriesSpecs(ctx: ChartContext): SeriesSpec[] {
  const specs: SeriesSpec[] = []
  for (const el of ctx.host.children) {
    if (el.hasAttribute("hidden")) continue
    if (el instanceof TecChartBar || el instanceof TecChartLine || el instanceof TecChartArea) {
      if (!el.key) continue
      specs.push({
        kind: el instanceof TecChartBar ? "bar" : el instanceof TecChartLine ? "line" : "area",
        key: el.key,
        element: el,
        color: el.color || undefined,
        stack: el.stack || undefined,
        radius: el instanceof TecChartBar ? parseRadius(el.radius) : [0, 0, 0, 0],
        maxBarSize: el instanceof TecChartBar ? el.maxBarSize : undefined,
        curve: el instanceof TecChartBar ? "linear" : el.curve,
        strokeWidth: el instanceof TecChartBar ? 0 : el.strokeWidth,
        dots: el instanceof TecChartBar ? false : el.dots,
        dashed: el instanceof TecChartLine ? el.dashed : false,
        fillOpacity: el instanceof TecChartArea ? el.fillOpacity : 1,
        gradient: el instanceof TecChartArea ? el.gradient : false,
        labels: ctx.childParts(el, TecChartLabelList),
        errors: el instanceof TecChartArea ? [] : ctx.childParts(el, TecChartErrorBar).filter((e) => e.key),
      })
    } else if (el instanceof TecChartScatter) {
      if (!el.key) continue
      specs.push({
        kind: "scatter",
        key: el.key,
        element: el,
        color: el.color || undefined,
        radius: [0, 0, 0, 0],
        curve: "linear",
        strokeWidth: 1.5,
        dots: false,
        dashed: false,
        fillOpacity: el.fillOpacity,
        gradient: false,
        shape: el.shape,
        line: el.line,
        nameKey: el.nameKey || undefined,
        labels: ctx.childParts(el, TecChartLabelList),
        errors: ctx.childParts(el, TecChartErrorBar).filter((e) => e.key),
      })
    }
  }
  const type = ctx.host.type
  if (specs.length || !type || !SHORTCUT_TYPES.has(type)) return specs
  // The `type` shortcut: one series per coloured config key (or per numeric field).
  const rows = ctx.rows
  const isNumeric = (key: string) => rows.some((row) => typeof row?.[key] === "number")
  const categoryKey = categoryKeyOf(ctx)
  let keys = Object.entries(ctx.config)
    .filter(([key, entry]) => entryColor(entry) && isNumeric(key) && key !== categoryKey)
    .map(([key]) => key)
  if (!keys.length && rows[0]) keys = Object.keys(rows[0]).filter((key) => key !== categoryKey && isNumeric(key))
  const kind = type as SeriesSpec["kind"]
  const stacked = ctx.host.stacked && kind !== "scatter"
  return keys.map((key) => ({
    kind,
    key,
    stack: stacked ? "stack" : undefined,
    radius: kind === "bar" && !stacked ? [4, 4, 4, 4] : [0, 0, 0, 0],
    curve: "natural",
    strokeWidth: kind === "line" ? 2 : 1,
    dots: false,
    dashed: false,
    fillOpacity: kind === "scatter" ? 1 : 0.4,
    gradient: false,
    shape: "circle",
  }))
}

function tickText(axis: TecChartAxis, value: unknown, index: number): string {
  if (axis.tickFormatter) return String(axis.tickFormatter(value, index))
  return value == null ? "" : String(value)
}

/** The value and error bar extents of one series over the drawn rows. */
interface Range {
  base: number
  top: number
}

function computeModel(ctx: ChartContext): CartesianModel | undefined {
  const { width: W, height: H, margin: m } = ctx
  const specs = seriesSpecs(ctx)
  const scatter = specs.some((s) => s.kind === "scatter")
  const horizontal = !scatter && ctx.host.orientation === "horizontal"
  const xAxis = xAxisOf(ctx)
  const yAxis = yAxisOf(ctx)
  const baseAxis = horizontal ? yAxis : xAxis
  const valueAxis = horizontal ? xAxis : yAxis
  const numericBase = scatter || baseAxis?.type === "number"
  const baseKey = categoryKeyOf(ctx)
  const all = ctx.rows
  const locale = ctx.locale

  // The brush window (row navigation only), then the rows that have a position on a number axis.
  const brushEl = scatter ? undefined : ctx.parts(TecChartBrush)[0]
  const [ws, we] = brushEl ? clampWindow(brushEl.startIndex, brushEl.endIndex, all.length) : [0, all.length - 1]
  let indexes: number[] = []
  for (let i = ws; i <= we; i++) indexes.push(i)
  if (numericBase) indexes = indexes.filter((i) => baseKey != null && numeric(all[i]?.[baseKey]) != null)
  const rows = indexes.map((i) => all[i] ?? {})
  const xs = numericBase ? rows.map((row) => numeric(row[baseKey!]) ?? 0) : []
  const hasBars = !scatter && specs.some((s) => s.kind === "bar")
  const drawn = scatter ? specs.filter((s) => s.kind !== "bar") : specs

  // Stacking: cumulative positive and negative sums per stack id and category.
  const stacks = new Map<string, { pos: number[]; neg: number[] }>()
  const ranges: (Range | null)[][] = drawn.map((spec) =>
    rows.map((row, i) => {
      const value = numeric(row?.[spec.key])
      if (value == null) return null
      if (!spec.stack || spec.kind === "scatter") return { base: 0, top: value }
      const id = `${spec.kind === "bar" ? "b" : "a"}:${spec.stack}`
      let stack = stacks.get(id)
      if (!stack) stacks.set(id, (stack = { pos: [], neg: [] }))
      const sums = value >= 0 ? stack.pos : stack.neg
      const base = sums[i] ?? 0
      sums[i] = base + value
      return { base, top: base + value }
    })
  )

  // Extents of the value axis and of a number category axis (data, error bars, references).
  const valueDirection = horizontal ? "x" : "y"
  let vLo = Infinity
  let vHi = -Infinity
  let bLo = Infinity
  let bHi = -Infinity
  const addValue = (n: number) => {
    vLo = Math.min(vLo, n)
    vHi = Math.max(vHi, n)
  }
  const addBase = (n: number) => {
    bLo = Math.min(bLo, n)
    bHi = Math.max(bHi, n)
  }
  ranges.forEach((series, si) => {
    const spec = drawn[si]!
    series.forEach((r, i) => {
      if (!r) return
      if (spec.kind !== "scatter") addValue(r.base)
      addValue(r.top)
      for (const err of spec.errors ?? []) {
        const direction = err.direction ?? valueDirection
        if (direction === valueDirection) {
          const ext = errorExtent(r.top, rows[i]?.[err.key])
          if (ext) ext.forEach(addValue)
        } else if (numericBase) {
          const ext = errorExtent(xs[i] ?? null, rows[i]?.[err.key])
          if (ext) ext.forEach(addBase)
        }
      }
    })
  })
  xs.forEach(addBase)
  const refExtents = referenceExtents(ctx, horizontal, numericBase)
  refExtents.value.forEach(addValue)
  refExtents.base.forEach(addBase)
  if (vLo > vHi) vLo = vHi = 0
  const values = resolveDomain(valueAxis?.domain, vLo, vHi, valueAxis?.tickCount ?? 5, true)
  let bases: ReturnType<typeof resolveDomain> | undefined
  if (numericBase) {
    if (bLo > bHi) bLo = bHi = 0
    if (hasBars) {
      // Room for half a bar on either side of the first and last rows.
      const half = (smallestStep(xs) || 1) / 2
      bLo -= half
      bHi += half
    }
    bases = resolveDomain(baseAxis?.domain, bLo, bHi, baseAxis?.tickCount ?? 5, false)
  }

  // The plot: the space left by the axes (and their titles).
  const fontSize = ctx.fontSize
  const titleBand = Math.ceil(fontSize * 1.25) + 6
  let yAxisSpace = 0
  if (yAxis) {
    yAxisSpace = yAxis.width
    if (yAxis.label) {
      const texts = horizontal
        ? numericBase
          ? bases!.ticks.map((t, i) => tickText(yAxis, t, i))
          : rows.map((row, i) => tickText(yAxis, baseKey ? row[baseKey] : i, i))
        : values.ticks.map((t, i) => tickText(yAxis, t, i))
      const widest = Math.max(0, ...texts.map((t) => ctx.measure(t)))
      yAxisSpace = Math.max(yAxis.width, Math.ceil(widest) + TICK_SIZE + yAxis.tickMargin + 2) + titleBand
    }
  }
  const xAxisSpace = xAxis ? xAxis.height + (xAxis.label ? titleBand : 0) : 0
  // The brush is drawn (as HTML) over the bottom of the plot box, under the x axis.
  const brushSpace = brushEl ? brushHeight(brushEl) + BRUSH_GAP : 0
  const plot: Rect = { x: m.start + yAxisSpace, y: m.top, w: 0, h: 0 }
  plot.w = Math.max(0, W - m.end - plot.x)
  plot.h = Math.max(0, H - m.bottom - brushSpace - xAxisSpace - plot.y)

  const valueDomain: [number, number] = values.domain
  const scale = horizontal ? linearScale(valueDomain, [plot.x, plot.x + plot.w]) : linearScale(valueDomain, [plot.y + plot.h, plot.y])
  const zero = scale(Math.min(Math.max(0, valueDomain[0]), valueDomain[1]))
  let baseScale: ((value: number) => number) | undefined
  let slots: CategorySlot[]
  if (bases) {
    baseScale = horizontal ? linearScale(bases.domain, [plot.y, plot.y + plot.h]) : linearScale(bases.domain, [plot.x, plot.x + plot.w])
    const length = horizontal ? plot.h : plot.w
    slots = numericSlots(
      xs.map((x) => baseScale!(x)),
      hasBars,
      length / 10
    )
  } else {
    slots = horizontal
      ? categoryScale(rows.length, plot.y, plot.y + plot.h, hasBars ? "band" : "point")
      : categoryScale(rows.length, plot.x, plot.x + plot.w, hasBars ? "band" : "point")
  }

  // Bar groups: one per stack id, one per unstacked bar series.
  const groups: string[] = []
  drawn.forEach((spec, i) => {
    if (spec.kind !== "bar") return
    const id = spec.stack ? `stack:${spec.stack}` : `bar:${i}`
    if (!groups.includes(id)) groups.push(id)
  })
  const bandSize = slots[0]?.size ?? 0
  const maxBarSize = drawn.find((s) => s.kind === "bar" && s.maxBarSize != null)?.maxBarSize
  const positions = barPositions(bandSize, groups.length, ctx.host.barCategoryGap, ctx.host.barGap, maxBarSize)

  // Bubble sizes.
  const zAxis = ctx.parts(TecChartZAxis)[0]
  const zKey = zAxis?.key
  const [rMin, rMax] = parseRange(zAxis?.range, [4, 4])
  let zMin = Infinity
  let zMax = -Infinity
  if (scatter && zKey)
    for (const row of rows) {
      const z = numeric(row[zKey])
      if (z == null) continue
      zMin = Math.min(zMin, z)
      zMax = Math.max(zMax, z)
    }

  const bounds: Rect = { x: 0, y: 0, w: W, h: H }
  const errors: ErrorDraw[] = []
  const candidates: (TextDraw & LabelBox)[] = []
  const series: SeriesDraw[] = drawn.map((spec, si) => {
    const color = ctx.seriesColor(spec.key, si, spec.color)
    const draw: SeriesDraw = { spec, color, bars: [], points: [], bases: [], marks: [] }
    const range = ranges[si]!
    if (spec.kind === "bar") {
      const group = groups.indexOf(spec.stack ? `stack:${spec.stack}` : `bar:${si}`)
      const position = positions[group]
      range.forEach((r, i) => {
        const slot = slots[i]
        if (!r || !slot || !position) return
        const a = scale(r.base)
        const b = scale(r.top)
        const row: ChartRow = rows[i] ?? {}
        const fill = spec.color ?? ((typeof row.fill === "string" && row.fill) || color)
        const negative = r.top < r.base
        const box = horizontal
          ? { x: Math.min(a, b), y: slot.start + position.offset, w: Math.abs(b - a), h: position.size }
          : { x: slot.start + position.offset, y: Math.min(a, b), w: position.size, h: Math.abs(b - a) }
        const d = roundedRect(box.x, box.y, box.w, box.h, spec.radius)
        draw.bars.push({ index: i, d, fill, negative, ...box })
      })
    } else if (spec.kind === "scatter") {
      range.forEach((r, i) => {
        if (!r) return
        const row = rows[i]!
        const zValue = zKey ? numeric(row[zKey]) : null
        const radius = bubbleRadius(zValue, zMin, zMax, rMin, rMax)
        const x = baseScale!(xs[i]!)
        const y = scale(r.top)
        draw.marks.push({ index: -1, series: si, row: i, r: radius, x, y, xValue: xs[i]!, yValue: r.top, zValue, d: symbolPath(spec.shape ?? "circle", x, y, radius) })
      })
    } else {
      range.forEach((r, i) => {
        const slot = slots[i]
        if (!r || !slot) {
          draw.points.push(null)
          draw.bases.push(null)
          return
        }
        const top = scale(r.top)
        const base = spec.stack ? scale(r.base) : zero
        draw.points.push(horizontal ? { x: top, y: slot.center } : { x: slot.center, y: top })
        draw.bases.push(horizontal ? { x: base, y: slot.center } : { x: slot.center, y: base })
      })
    }

    // Error bars, at the value end of every bar, point or mark.
    for (const err of spec.errors ?? []) {
      const direction = err.direction ?? valueDirection
      const along = direction === valueDirection ? "value" : "base"
      if (along === "base" && !numericBase) continue
      const at = (i: number, center: Point, value: number) => {
        const ext = errorExtent(along === "value" ? value : (xs[i] ?? null), rows[i]?.[err.key])
        if (!ext) return
        const s = along === "value" ? scale : baseScale!
        const [p0, p1] = [s(ext[0]), s(ext[1])]
        const vertical = direction === "y"
        errors.push({
          x1: vertical ? center.x : p0,
          x2: vertical ? center.x : p1,
          y1: vertical ? p0 : center.y,
          y2: vertical ? p1 : center.y,
          width: err.width,
          stroke: err.stroke || undefined,
        })
      }
      if (spec.kind === "bar")
        draw.bars.forEach((bar) => {
          const r = range[bar.index]!
          const end = scale(r.top)
          at(bar.index, horizontal ? { x: end, y: bar.y + bar.h / 2 } : { x: bar.x + bar.w / 2, y: end }, r.top)
        })
      else if (spec.kind === "scatter") draw.marks.forEach((mark) => at(mark.row, mark, mark.yValue))
      else draw.points.forEach((p, i) => p && at(i, p, range[i]!.top))
    }

    // Value labels.
    for (const list of spec.labels ?? []) {
      const key = list.key || spec.key
      const text = (i: number) => {
        const row = rows[i]
        const value = row?.[key]
        if (value == null || value === "") return ""
        return list.formatter ? String(list.formatter(value, row, indexes[i] ?? i)) : formatValue(value, locale)
      }
      const push = (t: string, placed: LabelPlacement | null) => {
        if (placed) candidates.push({ x: placed.x, y: placed.y, text: t, anchor: "middle", inside: placed.inside, moved: placed.moved, width: ctx.measure(t), height: fontSize })
      }
      if (spec.kind === "bar")
        draw.bars.forEach((bar) => {
          const t = text(bar.index)
          if (t) push(t, placeBarLabel(list.position, bar, ctx.measure(t), fontSize, list.offset, horizontal, bar.negative, bounds))
        })
      else if (spec.kind === "scatter")
        draw.marks.forEach((mark) => {
          const t = text(mark.row)
          if (t) push(t, placePointLabel(list.position, mark, mark.r, ctx.measure(t), fontSize, list.offset, bounds))
        })
      else
        draw.points.forEach((p, i) => {
          const t = p ? text(i) : ""
          if (t && p) push(t, placePointLabel(list.position, p, spec.dots ? 3 : 0, ctx.measure(t), fontSize, list.offset, bounds))
        })
    }
    return draw
  })

  // Value labels never overlap: labels that had to move yield to the others.
  const labels: TextDraw[] = avoidOverlaps(candidates).map((i) => {
    const { x, y, text, anchor, inside } = candidates[i]!
    return { x, y, text, anchor, inside }
  })

  // Scatter points in navigation order: by x, then series, then row.
  const points = series
    .flatMap((s) => s.marks)
    .sort((a, b) => a.xValue - b.xValue || a.series - b.series || a.row - b.row)
  points.forEach((p, i) => (p.index = i))

  const frame: CartesianFrame = {
    horizontal,
    plot,
    scale,
    valueDomain,
    numeric: numericBase,
    baseScale,
    baseDomain: bases?.domain,
    slots,
    indexes,
    categoryIndex: (value) => (baseKey ? all.findIndex((row) => String(row?.[baseKey] ?? "") === value) : -1),
  }
  const references = layoutReferences(frame, ctx)

  // Axis titles, in the space reserved for them.
  const axisLabels: CartesianModel["axisLabels"] = {}
  if (xAxis?.label) {
    axisLabels.x = { x: plot.x + plot.w / 2, y: plot.y + plot.h + xAxis.height + titleBand / 2, text: xAxis.label, anchor: "middle" }
  }
  if (yAxis?.label) {
    axisLabels.y = { x: m.start + titleBand / 2, y: plot.y + plot.h / 2, text: yAxis.label, anchor: "middle" }
  }

  let brush: BrushModel | undefined
  if (brushEl && all.length) {
    const texts = all.map((_, i) => categoryText(ctx, i))
    brush = { element: brushEl, start: ws, end: we, total: all.length, texts }
    const first = drawn.find((s) => s.kind !== "scatter")
    if (brushEl.preview && first) brush.preview = brushPreview(ctx, first, series[drawn.indexOf(first)]!.color, plot.w, brushHeight(brushEl))
  }

  return {
    kind: "cartesian",
    horizontal,
    plot,
    rows,
    indexes,
    numeric: numericBase,
    scatter,
    slots,
    hasBars,
    series,
    valueTicks: values.ticks.map((value) => ({ value, pos: scale(value) })),
    scale,
    valueDomain,
    baseTicks: bases ? bases.ticks.map((value) => ({ value, pos: baseScale!(value) })) : [],
    baseScale,
    baseDomain: bases?.domain,
    specs: drawn,
    points,
    references,
    errors,
    labels,
    axisLabels,
    brush,
    count: scatter ? points.length : rows.length,
  }
}

/** The first series over every row, scaled into the brush. */
function brushPreview(ctx: ChartContext, spec: SeriesSpec, color: string, width: number, height: number): BrushModel["preview"] {
  const total = ctx.rows.length
  const values = ctx.rows.map((row) => numeric(row?.[spec.key]))
  const present = values.filter((v): v is number => v != null)
  if (!present.length) return undefined
  const lo = Math.min(0, ...present)
  const hi = Math.max(0, ...present)
  const y = linearScale([lo, hi === lo ? lo + 1 : hi], [height - 2, 2])
  const top: Point[] = []
  const base: Point[] = []
  values.forEach((v, i) => {
    if (v == null) return
    const x = brushPosition(i, total, width)
    top.push({ x, y: y(v) })
    base.push({ x, y: y(Math.max(lo, 0)) })
  })
  return { area: areaPath(top, base, "monotone"), line: linePath(top, "monotone"), color }
}

/** Splits point indexes into runs without missing values (lines break at gaps). */
function segments(points: (Point | null)[]): number[][] {
  const out: number[][] = []
  let current: number[] = []
  points.forEach((p, i) => {
    if (p) current.push(i)
    else if (current.length) {
      out.push(current)
      current = []
    }
  })
  if (current.length) out.push(current)
  return out
}

function renderCartesian(model: CartesianModel, ctx: ChartContext): SVGTemplateResult {
  const { plot, horizontal, slots, series } = model
  const grid = ctx.parts(TecChartGrid)[0]
  const tooltip = ctx.tooltip
  const active = ctx.active
  const activeSlot = !model.scatter && active >= 0 ? slots[active] : undefined
  const activePoint = model.scatter && active >= 0 ? model.points[active] : undefined

  let gridLines: SVGTemplateResult | typeof nothing = nothing
  if (grid) {
    const both = grid.horizontal || grid.vertical
    const drawHorizontal = both ? grid.horizontal : !horizontal
    const drawVertical = both ? grid.vertical : horizontal
    const valuePositions = model.valueTicks.map((t) => t.pos)
    const categoryPositions = model.numeric ? model.baseTicks.map((t) => t.pos) : slots.map((s) => s.center)
    const hPositions = horizontal ? categoryPositions : valuePositions
    const vPositions = horizontal ? valuePositions : categoryPositions
    gridLines = svg`<g class="grid" ?data-dashed=${grid.dashed}>
      ${drawHorizontal ? hPositions.map((y) => svg`<line x1=${plot.x} x2=${plot.x + plot.w} y1=${y} y2=${y}></line>`) : nothing}
      ${drawVertical ? vPositions.map((x) => svg`<line x1=${x} x2=${x} y1=${plot.y} y2=${plot.y + plot.h}></line>`) : nothing}
    </g>`
  }

  let cursor: SVGTemplateResult | typeof nothing = nothing
  if (tooltip && !tooltip.hideCursor) {
    if (activePoint) {
      // A crosshair through the active point.
      cursor = svg`<g class="cursor-cross">
        <line class="cursor-line" x1=${activePoint.x} x2=${activePoint.x} y1=${plot.y} y2=${plot.y + plot.h}></line>
        <line class="cursor-line" x1=${plot.x} x2=${plot.x + plot.w} y1=${activePoint.y} y2=${activePoint.y}></line>
      </g>`
    } else if (activeSlot) {
      if (model.hasBars) {
        cursor = horizontal
          ? svg`<rect class="cursor-band" x=${plot.x} y=${activeSlot.start} width=${plot.w} height=${activeSlot.size}></rect>`
          : svg`<rect class="cursor-band" x=${activeSlot.start} y=${plot.y} width=${activeSlot.size} height=${plot.h}></rect>`
      } else {
        cursor = horizontal
          ? svg`<line class="cursor-line" x1=${plot.x} x2=${plot.x + plot.w} y1=${activeSlot.center} y2=${activeSlot.center}></line>`
          : svg`<line class="cursor-line" x1=${activeSlot.center} x2=${activeSlot.center} y1=${plot.y} y2=${plot.y + plot.h}></line>`
      }
    }
  }

  const gradients = series
    .map((s, i) => ({ s, i }))
    .filter(({ s }) => s.spec.kind === "area" && s.spec.gradient)
    .map(
      ({ s, i }) => svg`<linearGradient id="fill-${i}" x1="0" y1="0" x2=${horizontal ? "1" : "0"} y2=${horizontal ? "0" : "1"}>
        <stop offset="5%" stop-color=${s.color} stop-opacity="0.8"></stop>
        <stop offset="95%" stop-color=${s.color} stop-opacity="0.1"></stop>
      </linearGradient>`
    )

  const areas = series.map((s, i) => {
    if (s.spec.kind !== "area") return nothing
    const parts = segments(s.points)
    return svg`<g class="reveal">
      ${parts.map((idx) => {
        const top = idx.map((j) => s.points[j]!)
        const base = idx.map((j) => s.bases[j]!)
        return svg`
          <path class="area series-path" d=${areaPath(top, base, s.spec.curve)} style=${`d: path("${areaPath(top, base, s.spec.curve)}")`}
            fill=${s.spec.gradient ? `url(#fill-${i})` : s.color} fill-opacity=${s.spec.gradient ? 1 : s.spec.fillOpacity} stroke="none"></path>
          <path class="series-path" d=${linePath(top, s.spec.curve)} style=${`d: path("${linePath(top, s.spec.curve)}")`}
            fill="none" stroke=${s.color} stroke-width=${s.spec.strokeWidth}></path>`
      })}
    </g>`
  })

  const bars = series.map((s) =>
    s.spec.kind === "bar"
      ? svg`<g class="bars">${s.bars.map(
          (bar) => svg`<path class="bar" d=${bar.d} style=${`d: path("${bar.d}")`} fill=${bar.fill} ?data-negative=${bar.negative} data-index=${bar.index}></path>`
        )}</g>`
      : nothing
  )

  const lines = series.map((s) => {
    if (s.spec.kind !== "line") return nothing
    return svg`<g class="reveal">${segments(s.points).map((idx) => {
      const d = linePath(
        idx.map((j) => s.points[j]!),
        s.spec.curve
      )
      return svg`<path class="series-path" d=${d} style=${`d: path("${d}")`} fill="none" stroke=${s.color}
        stroke-width=${s.spec.strokeWidth} stroke-dasharray=${s.spec.dashed ? "4 4" : nothing}
        stroke-linejoin="round" stroke-linecap="round"></path>`
    })}</g>`
  })

  const scatters = series.map((s) => {
    if (s.spec.kind !== "scatter") return nothing
    const connected = s.spec.line && s.marks.length > 1 ? linePath([...s.marks].sort((a, b) => a.xValue - b.xValue)) : ""
    return svg`<g class="scatter">
      ${connected ? svg`<path class="series-path" d=${connected} fill="none" stroke=${s.color} stroke-width=${s.spec.strokeWidth} stroke-linejoin="round"></path>` : nothing}
      ${s.marks.map(
        (mark) => svg`<path class="symbol" d=${mark.d} fill=${s.color} fill-opacity=${s.spec.fillOpacity} data-index=${mark.index}></path>`
      )}
    </g>`
  })

  const dots = series.map((s) => {
    if (s.spec.kind === "bar" || s.spec.kind === "scatter") return nothing
    return svg`
      ${s.spec.dots ? s.points.map((p) => (p ? svg`<circle class="dot" cx=${p.x} cy=${p.y} r="3" stroke=${s.color} stroke-width=${Math.max(1, s.spec.strokeWidth)}></circle>` : nothing)) : nothing}
      ${tooltip && active >= 0 && !model.scatter && s.points[active] ? svg`<circle class="active-dot" cx=${s.points[active]!.x} cy=${s.points[active]!.y} r="4" fill=${s.color}></circle>` : nothing}
    `
  })

  const activeMark = activePoint
    ? svg`<path class="active-symbol" d=${symbolPath(series[activePoint.series]?.spec.shape ?? "circle", activePoint.x, activePoint.y, activePoint.r + 3)}></path>`
    : nothing

  const clip = model.references.some((r) => r.clip)
    ? svg`<clipPath id="plot-clip"><rect x=${plot.x} y=${plot.y} width=${plot.w} height=${plot.h}></rect></clipPath>`
    : nothing

  return svg`
    <defs>${gradients}${clip}</defs>
    ${gridLines}
    ${renderReferenceAreas(model.references, ctx.rtl)}
    ${cursor}
    ${areas}
    ${bars}
    ${lines}
    ${scatters}
    ${dots}
    ${model.errors.length ? svg`<g class="errors">${renderErrors(model.errors)}</g>` : nothing}
    ${renderReferenceMarks(model.references, ctx.rtl)}
    ${activeMark}
    ${model.labels.length ? svg`<g class="labels">${model.labels.map((l) => renderText(l, "value-label", ctx.rtl))}</g>` : nothing}
    ${renderAxes(model, ctx)}
  `
}

function renderAxes(model: CartesianModel, ctx: ChartContext): SVGTemplateResult {
  const { plot, horizontal, slots, rows } = model
  const key = categoryKeyOf(ctx)
  const categories = rows.map((row, i) => (key ? row?.[key] : model.indexes[i]))
  const xAxis = xAxisOf(ctx)
  const yAxis = yAxisOf(ctx)
  const out: SVGTemplateResult[] = []
  const fontSize = ctx.fontSize
  const categoryItems = (axis: TecChartAxis) =>
    model.numeric
      ? model.baseTicks.map((t, i) => ({ coordinate: t.pos, text: tickText(axis, t.value, i) }))
      : slots.map((s, i) => ({ coordinate: s.center, text: tickText(axis, categories[i], i) }))

  if (xAxis) {
    const y = plot.y + plot.h
    const items = horizontal ? model.valueTicks.map((t, i) => ({ coordinate: t.pos, text: tickText(xAxis, t.value, i) })) : categoryItems(xAxis)
    // Labels may extend into the chart's margins (the first and last category sit at the edges of
    // the plot), and are only thinned or nudged where they would leave the chart.
    const shown = thinTicks(
      items.map((t) => t.coordinate),
      (i) => ctx.measure(items[i]!.text),
      0,
      ctx.width,
      xAxis.minTickGap
    )
    const ty = y + TICK_SIZE + xAxis.tickMargin
    out.push(svg`<g class="x-axis">
      ${xAxis.axisLine ? svg`<line class="axis-line" x1=${plot.x} x2=${plot.x + plot.w} y1=${y} y2=${y}></line>` : nothing}
      ${shown.map(
        (t) => svg`
          ${xAxis.tickLine ? svg`<line class="tick-line" x1=${t.coordinate} x2=${t.coordinate} y1=${y} y2=${y + TICK_SIZE}></line>` : nothing}
          <text class="tick" x=${t.labelCoordinate} y=${ty} dy="0.71em" text-anchor="middle">${items[t.index]!.text}</text>`
      )}
      ${model.axisLabels.x ? renderText(model.axisLabels.x, "axis-label", ctx.rtl) : nothing}
    </g>`)
  }

  if (yAxis) {
    const x = plot.x
    const items = horizontal ? categoryItems(yAxis) : model.valueTicks.map((t, i) => ({ coordinate: t.pos, text: tickText(yAxis, t.value, i) }))
    // Keep labels from overlapping (walk from the bottom for values, from the top for categories).
    const fromTop = horizontal && !model.numeric
    let limit = fromTop ? -Infinity : Infinity
    const visible = items.filter((t) => {
      const ok = fromTop ? t.coordinate - fontSize / 2 >= limit : t.coordinate + fontSize / 2 <= limit
      if (ok) limit = fromTop ? t.coordinate + fontSize / 2 + yAxis.minTickGap : t.coordinate - fontSize / 2 - yAxis.minTickGap
      return ok
    })
    const tx = x - TICK_SIZE - yAxis.tickMargin
    out.push(svg`<g class="y-axis">
      ${yAxis.axisLine ? svg`<line class="axis-line" x1=${x} x2=${x} y1=${plot.y} y2=${plot.y + plot.h}></line>` : nothing}
      ${visible.map(
        (t) => svg`
          ${yAxis.tickLine ? svg`<line class="tick-line" x1=${x - TICK_SIZE} x2=${x} y1=${t.coordinate} y2=${t.coordinate}></line>` : nothing}
          <text class="tick" x=${tx} y=${t.coordinate} dy="0.355em" text-anchor=${textAnchor("end", ctx.rtl)}>${t.text}</text>`
      )}
      ${model.axisLabels.y
        ? svg`<text class="axis-label" data-rotated x=${model.axisLabels.y.x} y=${model.axisLabels.y.y} dy="0.355em" text-anchor="middle">${model.axisLabels.y.text}</text>`
        : nothing}
    </g>`)
  }
  return svg`${out}`
}

/**
 * The category's name as text: the tooltip's formatted label when it is text, else the config label
 * or raw value. `index` is a row of `rows` (the chart's data by default).
 */
export function categoryText(ctx: ChartContext, index: number, rows: ChartRow[] = ctx.rows): string {
  const key = categoryKeyOf(ctx)
  const raw = key ? rows[index]?.[key] : index + 1
  const tooltip = ctx.tooltip
  if (tooltip?.labelFormatter && key) {
    const value = typeof raw === "string" ? (ctx.config[raw]?.label ?? raw) : raw
    const formatted = tooltip.labelFormatter(value, [])
    if (typeof formatted === "string") return formatted
  }
  return ctx.text(raw)
}

/** The label of a config key, else the key itself. */
const labelOf = (ctx: ChartContext, key: string | undefined, fallback = "") => (key ? (ctx.config[key]?.label ?? key) : fallback)

/** An error as the data table shows it: `±5` or `−2 / +4`. */
function errorText(error: unknown, locale: string | undefined): string {
  if (error == null || error === "") return ""
  if (Array.isArray(error)) return `−${formatValue(Math.abs(Number(error[0])), locale)} / +${formatValue(Math.abs(Number(error[1] ?? error[0])), locale)}`
  const n = Number(error)
  return Number.isFinite(n) ? `±${formatValue(Math.abs(n), locale)}` : String(error)
}

/** Every scatter point of every row (the data table ignores the brush), in navigation order. */
function allScatterPoints(model: CartesianModel, ctx: ChartContext) {
  const key = categoryKeyOf(ctx)
  const out: { series: number; row: ChartRow; x: number; y: number }[] = []
  model.specs.forEach((spec, si) => {
    if (spec.kind !== "scatter" || !key) return
    for (const row of ctx.rows) {
      const x = numeric(row?.[key])
      const y = numeric(row?.[spec.key])
      if (x != null && y != null) out.push({ series: si, row, x, y })
    }
  })
  return out.sort((a, b) => a.x - b.x || a.series - b.series)
}

function scatterTable(model: CartesianModel, ctx: ChartContext) {
  const key = categoryKeyOf(ctx)
  const zKey = ctx.parts(TecChartZAxis)[0]?.key
  const scatters = model.specs.filter((s) => s.kind === "scatter")
  const yAxis = yAxisOf(ctx)
  const xAxis = xAxisOf(ctx)
  const yHeader = yAxis?.label || (scatters.length === 1 ? labelOf(ctx, scatters[0]!.key) : "y")
  const errorKeys = [...new Set(scatters.flatMap((s) => (s.errors ?? []).map((e) => e.key)))]
  const points = allScatterPoints(model, ctx)
  const locale = ctx.locale
  const multiple = scatters.length > 1
  const nameKey = scatters.find((s) => s.nameKey)?.nameKey
  const seriesName = (p: (typeof points)[number]) => labelOf(ctx, model.specs[p.series]!.key)
  return html`<table part="table" class="sr-only">
    <caption>${ctx.name()}</caption>
    <thead>
      <tr>
        <th scope="col">${nameKey ? labelOf(ctx, nameKey) : multiple ? "Series" : "#"}</th>
        ${nameKey && multiple ? html`<th scope="col">Series</th>` : nothing}
        <th scope="col">${xAxis?.label || labelOf(ctx, key, "x")}</th>
        <th scope="col">${yHeader}</th>
        ${zKey ? html`<th scope="col">${labelOf(ctx, zKey)}</th>` : nothing}
        ${errorKeys.map((k) => html`<th scope="col">${labelOf(ctx, k)}</th>`)}
      </tr>
    </thead>
    <tbody>
      ${points.map(
        (p, i) => html`<tr>
          <th scope="row">${nameKey ? ctx.text(p.row[model.specs[p.series]!.nameKey ?? nameKey]) : multiple ? seriesName(p) : i + 1}</th>
          ${nameKey && multiple ? html`<td>${seriesName(p)}</td>` : nothing}
          <td>${formatValue(p.x, locale)}</td>
          <td>${formatValue(p.y, locale)}</td>
          ${zKey ? html`<td>${formatValue(p.row[zKey], locale)}</td>` : nothing}
          ${errorKeys.map((k) => html`<td>${(model.specs[p.series]!.errors ?? []).some((e) => e.key === k) ? errorText(p.row[k], locale) : ""}</td>`)}
        </tr>`
      )}
    </tbody>
  </table>`
}

export const cartesianKind: ChartKind<CartesianModel> = {
  id: "cartesian",
  mirrored: true,
  claims: () => true,
  label(ctx) {
    const kind = seriesSpecs(ctx)[0]?.kind ?? ctx.host.type
    return kind ? `${kind[0]!.toUpperCase()}${kind.slice(1)} chart` : "Chart"
  },
  model: computeModel,
  render: renderCartesian,
  payload(model, index, ctx) {
    if (model.scatter) {
      const point = model.points[index]
      if (!point) return { label: undefined, items: [] }
      const s = model.series[point.series]!
      const row = model.rows[point.row]
      const xKey = categoryKeyOf(ctx) ?? "x"
      const zKey = ctx.parts(TecChartZAxis)[0]?.key
      const items = [
        { dataKey: xKey, name: xKey, value: point.xValue, color: s.color, row },
        { dataKey: s.spec.key, name: s.spec.key, value: point.yValue, color: s.color, row },
      ]
      if (zKey) items.push({ dataKey: zKey, name: zKey, value: point.zValue as number, color: s.color, row })
      const name = s.spec.nameKey ? row?.[s.spec.nameKey] : undefined
      return { label: name != null && name !== "" ? name : s.spec.key, items }
    }
    const row = model.rows[index]
    if (!row) return { label: undefined, items: [] }
    const key = categoryKeyOf(ctx)
    return {
      label: key ? row[key] : index,
      items: model.series.map((s) => ({ dataKey: s.spec.key, name: s.spec.key, value: row[s.spec.key], color: s.color, row })),
    }
  },
  anchor(model, index) {
    if (model.scatter) {
      const point = model.points[index]
      return point ? { x: point.x, y: point.y } : undefined
    }
    const slot = model.slots[index]
    if (!slot) return undefined
    return model.horizontal ? { x: model.plot.x + model.plot.w / 2, y: slot.center } : { x: slot.center, y: model.plot.y + model.plot.h / 2 }
  },
  hit(model, point) {
    const { plot } = model
    if (model.scatter) return nearestPoint(model.points, point, 24)
    if (point.x < plot.x || point.x > plot.x + plot.w || point.y < plot.y || point.y > plot.y + plot.h) return -1
    const position = model.horizontal ? point.y : point.x
    if (model.numeric)
      return nearestIndex(
        model.slots.map((s) => s.center),
        position
      )
    return categoryAt(model.slots, position)
  },
  table(model, ctx) {
    const specs = model.specs
    if (!specs.length || !ctx.rows.length) return nothing
    if (model.scatter) return scatterTable(model, ctx)
    const key = categoryKeyOf(ctx)
    const config = ctx.config
    const locale = ctx.locale
    const errorColumns = specs.flatMap((s) => (s.errors ?? []).map((e) => ({ spec: s, key: e.key })))
    return html`<table part="table" class="sr-only">
      <caption>${ctx.name()}</caption>
      <thead>
        <tr>
          <th scope="col">${key ? (config[key]?.label ?? key) : "#"}</th>
          ${specs.map((s) => html`<th scope="col">${config[s.key]?.label ?? s.key}</th>`)}
          ${errorColumns.map((c) => html`<th scope="col">${labelOf(ctx, c.key)}</th>`)}
        </tr>
      </thead>
      <tbody>
        ${ctx.rows.map(
          (row, i) => html`<tr>
            <th scope="row">${model.numeric && key ? formatValue(row?.[key], locale) : categoryText(ctx, i)}</th>
            ${specs.map((s) => html`<td>${formatValue(row?.[s.key], locale)}</td>`)}
            ${errorColumns.map((c) => html`<td>${errorText(row?.[c.key], locale)}</td>`)}
          </tr>`
        )}
      </tbody>
    </table>`
  },
  legend(model) {
    return model.series.map((s) => ({ dataKey: s.spec.key, color: s.color }))
  },
  overlay(model, ctx) {
    return model.brush ? renderBrush(model.brush, model.plot, ctx) : nothing
  },
}
