/**
 * @module chart-cartesian
 * The cartesian kind: bar, line and area series (mixed freely, like a composed chart) on a category
 * axis and a value axis, with the grid, the axes and the cursor.
 */
import { html, nothing, svg, type SVGTemplateResult } from "lit"
import { entryColor, formatValue, type ChartRow } from "./chart-config.js"
import { areaPath, barPositions, categoryAt, categoryScale, linePath, linearScale, niceTicks, roundedRect, thinTicks, type CategorySlot, type ChartCurve, type Point } from "./chart-engine.js"
import { numeric, type ChartContext, type ChartKind, type ChartModelBase, type Rect } from "./chart-kind.js"
import { TecChartArea, TecChartAxis, TecChartBar, TecChartGrid, TecChartLine, TecChartXAxis, TecChartYAxis } from "./chart-parts.js"

export interface SeriesSpec {
  kind: "bar" | "line" | "area"
  key: string
  /** The series element (absent for series generated by the `type` shortcut). */
  element?: Element
  color?: string
  stack?: string
  radius: [number, number, number, number]
  maxBarSize?: number
  curve: ChartCurve
  strokeWidth: number
  dots: boolean
  dashed: boolean
  fillOpacity: number
  gradient: boolean
}

export interface SeriesDraw {
  spec: SeriesSpec
  color: string
  bars: { index: number; d: string; fill: string; negative: boolean; x: number; y: number; w: number; h: number }[]
  /** Line/area points per category (null where the value is missing). */
  points: (Point | null)[]
  bases: (Point | null)[]
}

export interface CartesianModel extends ChartModelBase {
  kind: "cartesian"
  horizontal: boolean
  slots: CategorySlot[]
  hasBars: boolean
  series: SeriesDraw[]
  valueTicks: { value: number; pos: number }[]
  /** Maps a value to its position on the value axis. */
  scale: (value: number) => number
  specs: SeriesSpec[]
}

export const TICK_SIZE = 6

function parseRadius(value: string | undefined): [number, number, number, number] {
  const parts = String(value ?? "0")
    .split(/[\s,]+/)
    .filter(Boolean)
    .map((v) => Number.parseFloat(v) || 0)
  if (parts.length >= 4) return [parts[0]!, parts[1]!, parts[2]!, parts[3]!]
  const r = parts[0] ?? 0
  return [r, r, r, r]
}

const xAxisOf = (ctx: ChartContext) => ctx.parts(TecChartXAxis)[0]
const yAxisOf = (ctx: ChartContext) => ctx.parts(TecChartYAxis)[0]

/** The data field of the categories: the chart's `category-key`, else the category axis' `key`. */
export function categoryKeyOf(ctx: ChartContext): string | undefined {
  if (ctx.host.categoryKey) return ctx.host.categoryKey
  const x = xAxisOf(ctx)?.key
  const y = yAxisOf(ctx)?.key
  return ctx.host.orientation === "horizontal" ? (y ?? x) : (x ?? y)
}

const SHORTCUT_TYPES = new Set(["bar", "line", "area"])

export function seriesSpecs(ctx: ChartContext): SeriesSpec[] {
  const specs: SeriesSpec[] = []
  for (const el of ctx.host.children) {
    if (el.hasAttribute("hidden")) continue
    if (el instanceof TecChartBar || el instanceof TecChartLine || el instanceof TecChartArea) {
      if (!el.key) continue
      specs.push({
        kind: el instanceof TecChartBar ? "bar" : el instanceof TecChartLine ? "line" : "area",
        key: el.key,
        element: el,
        color: el.color || undefined,
        stack: el.stack || undefined,
        radius: el instanceof TecChartBar ? parseRadius(el.radius) : [0, 0, 0, 0],
        maxBarSize: el instanceof TecChartBar ? el.maxBarSize : undefined,
        curve: el instanceof TecChartBar ? "linear" : el.curve,
        strokeWidth: el instanceof TecChartBar ? 0 : el.strokeWidth,
        dots: el instanceof TecChartBar ? false : el.dots,
        dashed: el instanceof TecChartLine ? el.dashed : false,
        fillOpacity: el instanceof TecChartArea ? el.fillOpacity : 1,
        gradient: el instanceof TecChartArea ? el.gradient : false,
      })
    }
  }
  const type = ctx.host.type
  if (specs.length || !type || !SHORTCUT_TYPES.has(type)) return specs
  // The `type` shortcut: one series per coloured config key (or per numeric field).
  const rows = ctx.rows
  const isNumeric = (key: string) => rows.some((row) => typeof row?.[key] === "number")
  let keys = Object.entries(ctx.config)
    .filter(([key, entry]) => entryColor(entry) && isNumeric(key))
    .map(([key]) => key)
  if (!keys.length && rows[0]) keys = Object.keys(rows[0]).filter((key) => key !== categoryKeyOf(ctx) && isNumeric(key))
  const kind = type as SeriesSpec["kind"]
  const stacked = ctx.host.stacked
  return keys.map((key) => ({
    kind,
    key,
    stack: stacked ? "stack" : undefined,
    radius: kind === "bar" && !stacked ? [4, 4, 4, 4] : [0, 0, 0, 0],
    curve: "natural",
    strokeWidth: kind === "line" ? 2 : 1,
    dots: false,
    dashed: false,
    fillOpacity: 0.4,
    gradient: false,
  }))
}

function computeModel(ctx: ChartContext): CartesianModel | undefined {
  const { width: W, height: H, rows, margin: m } = ctx
  const specs = seriesSpecs(ctx)
  const horizontal = ctx.host.orientation === "horizontal"
  const xAxis = xAxisOf(ctx)
  const yAxis = yAxisOf(ctx)
  const plot: Rect = { x: m.start + (yAxis ? yAxis.width : 0), y: m.top, w: 0, h: 0 }
  plot.w = Math.max(0, W - m.end - plot.x)
  plot.h = Math.max(0, H - m.bottom - (xAxis ? xAxis.height : 0) - plot.y)

  const hasBars = specs.some((s) => s.kind === "bar")
  const count = rows.length
  const slots = horizontal
    ? categoryScale(count, plot.y, plot.y + plot.h, hasBars ? "band" : "point")
    : categoryScale(count, plot.x, plot.x + plot.w, hasBars ? "band" : "point")

  // Stacking: cumulative positive and negative sums per stack id and category.
  const stacks = new Map<string, { pos: number[]; neg: number[] }>()
  const ranges = specs.map((spec) =>
    rows.map((row, i) => {
      const value = numeric(row?.[spec.key])
      if (value == null) return null
      if (!spec.stack) return { base: 0, top: value }
      const id = `${spec.kind === "bar" ? "b" : "a"}:${spec.stack}`
      let stack = stacks.get(id)
      if (!stack) stacks.set(id, (stack = { pos: [], neg: [] }))
      const sums = value >= 0 ? stack.pos : stack.neg
      const base = sums[i] ?? 0
      sums[i] = base + value
      return { base, top: base + value }
    })
  )
  let min = 0
  let max = 0
  for (const series of ranges)
    for (const r of series) {
      if (!r) continue
      min = Math.min(min, r.base, r.top)
      max = Math.max(max, r.base, r.top)
    }
  const valueAxis = horizontal ? xAxis : yAxis
  const ticks = niceTicks(min, max === min ? min + 1 : max, valueAxis?.tickCount ?? 5)
  const domain: [number, number] = [ticks[0]!, ticks[ticks.length - 1]!]
  const scale = horizontal ? linearScale(domain, [plot.x, plot.x + plot.w]) : linearScale(domain, [plot.y + plot.h, plot.y])
  const zero = scale(Math.min(Math.max(0, domain[0]), domain[1]))

  // Bar groups: one per stack id, one per unstacked bar series.
  const groups: string[] = []
  specs.forEach((spec, i) => {
    if (spec.kind !== "bar") return
    const id = spec.stack ? `stack:${spec.stack}` : `bar:${i}`
    if (!groups.includes(id)) groups.push(id)
  })
  const bandSize = slots[0]?.size ?? 0
  const maxBarSize = specs.find((s) => s.kind === "bar" && s.maxBarSize != null)?.maxBarSize
  const positions = barPositions(bandSize, groups.length, ctx.host.barCategoryGap, ctx.host.barGap, maxBarSize)

  const series: SeriesDraw[] = specs.map((spec, si) => {
    const color = ctx.seriesColor(spec.key, si, spec.color)
    const draw: SeriesDraw = { spec, color, bars: [], points: [], bases: [] }
    const range = ranges[si]!
    if (spec.kind === "bar") {
      const group = groups.indexOf(spec.stack ? `stack:${spec.stack}` : `bar:${si}`)
      const position = positions[group]
      range.forEach((r, i) => {
        const slot = slots[i]
        if (!r || !slot || !position) return
        const a = scale(r.base)
        const b = scale(r.top)
        const row: ChartRow = rows[i] ?? {}
        const fill = spec.color ?? ((typeof row.fill === "string" && row.fill) || color)
        const negative = r.top < r.base
        const box = horizontal
          ? { x: Math.min(a, b), y: slot.start + position.offset, w: Math.abs(b - a), h: position.size }
          : { x: slot.start + position.offset, y: Math.min(a, b), w: position.size, h: Math.abs(b - a) }
        const d = roundedRect(box.x, box.y, box.w, box.h, spec.radius)
        draw.bars.push({ index: i, d, fill, negative, ...box })
      })
    } else {
      range.forEach((r, i) => {
        const slot = slots[i]
        if (!r || !slot) {
          draw.points.push(null)
          draw.bases.push(null)
          return
        }
        const top = scale(r.top)
        const base = spec.stack ? scale(r.base) : zero
        draw.points.push(horizontal ? { x: top, y: slot.center } : { x: slot.center, y: top })
        draw.bases.push(horizontal ? { x: base, y: slot.center } : { x: slot.center, y: base })
      })
    }
    return draw
  })

  return {
    kind: "cartesian",
    horizontal,
    plot,
    slots,
    hasBars,
    series,
    valueTicks: ticks.map((value) => ({ value, pos: scale(value) })),
    scale,
    specs,
    count,
  }
}

/** Splits point indexes into runs without missing values (lines break at gaps). */
function segments(points: (Point | null)[]): number[][] {
  const out: number[][] = []
  let current: number[] = []
  points.forEach((p, i) => {
    if (p) current.push(i)
    else if (current.length) {
      out.push(current)
      current = []
    }
  })
  if (current.length) out.push(current)
  return out
}

function renderCartesian(model: CartesianModel, ctx: ChartContext): SVGTemplateResult {
  const { plot, horizontal, slots, series } = model
  const grid = ctx.parts(TecChartGrid)[0]
  const tooltip = ctx.tooltip
  const active = ctx.active
  const activeSlot = active >= 0 ? slots[active] : undefined
  const showCursor = tooltip && !tooltip.hideCursor && activeSlot

  let gridLines: SVGTemplateResult | typeof nothing = nothing
  if (grid) {
    const both = grid.horizontal || grid.vertical
    const drawHorizontal = both ? grid.horizontal : !horizontal
    const drawVertical = both ? grid.vertical : horizontal
    const valuePositions = model.valueTicks.map((t) => t.pos)
    const categoryPositions = slots.map((s) => s.center)
    const hPositions = horizontal ? categoryPositions : valuePositions
    const vPositions = horizontal ? valuePositions : categoryPositions
    gridLines = svg`<g class="grid" ?data-dashed=${grid.dashed}>
      ${drawHorizontal ? hPositions.map((y) => svg`<line x1=${plot.x} x2=${plot.x + plot.w} y1=${y} y2=${y}></line>`) : nothing}
      ${drawVertical ? vPositions.map((x) => svg`<line x1=${x} x2=${x} y1=${plot.y} y2=${plot.y + plot.h}></line>`) : nothing}
    </g>`
  }

  let cursor: SVGTemplateResult | typeof nothing = nothing
  if (showCursor) {
    if (model.hasBars) {
      cursor = horizontal
        ? svg`<rect class="cursor-band" x=${plot.x} y=${activeSlot.start} width=${plot.w} height=${activeSlot.size}></rect>`
        : svg`<rect class="cursor-band" x=${activeSlot.start} y=${plot.y} width=${activeSlot.size} height=${plot.h}></rect>`
    } else {
      cursor = horizontal
        ? svg`<line class="cursor-line" x1=${plot.x} x2=${plot.x + plot.w} y1=${activeSlot.center} y2=${activeSlot.center}></line>`
        : svg`<line class="cursor-line" x1=${activeSlot.center} x2=${activeSlot.center} y1=${plot.y} y2=${plot.y + plot.h}></line>`
    }
  }

  const gradients = series
    .map((s, i) => ({ s, i }))
    .filter(({ s }) => s.spec.kind === "area" && s.spec.gradient)
    .map(
      ({ s, i }) => svg`<linearGradient id="fill-${i}" x1="0" y1="0" x2=${horizontal ? "1" : "0"} y2=${horizontal ? "0" : "1"}>
        <stop offset="5%" stop-color=${s.color} stop-opacity="0.8"></stop>
        <stop offset="95%" stop-color=${s.color} stop-opacity="0.1"></stop>
      </linearGradient>`
    )

  const areas = series.map((s, i) => {
    if (s.spec.kind !== "area") return nothing
    const parts = segments(s.points)
    return svg`<g class="reveal">
      ${parts.map((idx) => {
        const top = idx.map((j) => s.points[j]!)
        const base = idx.map((j) => s.bases[j]!)
        return svg`
          <path class="area series-path" d=${areaPath(top, base, s.spec.curve)} style=${`d: path("${areaPath(top, base, s.spec.curve)}")`}
            fill=${s.spec.gradient ? `url(#fill-${i})` : s.color} fill-opacity=${s.spec.gradient ? 1 : s.spec.fillOpacity} stroke="none"></path>
          <path class="series-path" d=${linePath(top, s.spec.curve)} style=${`d: path("${linePath(top, s.spec.curve)}")`}
            fill="none" stroke=${s.color} stroke-width=${s.spec.strokeWidth}></path>`
      })}
    </g>`
  })

  const bars = series.map((s) =>
    s.spec.kind === "bar"
      ? svg`<g class="bars">${s.bars.map(
          (bar) => svg`<path class="bar" d=${bar.d} style=${`d: path("${bar.d}")`} fill=${bar.fill} ?data-negative=${bar.negative} data-index=${bar.index}></path>`
        )}</g>`
      : nothing
  )

  const lines = series.map((s) => {
    if (s.spec.kind !== "line") return nothing
    return svg`<g class="reveal">${segments(s.points).map((idx) => {
      const d = linePath(
        idx.map((j) => s.points[j]!),
        s.spec.curve
      )
      return svg`<path class="series-path" d=${d} style=${`d: path("${d}")`} fill="none" stroke=${s.color}
        stroke-width=${s.spec.strokeWidth} stroke-dasharray=${s.spec.dashed ? "4 4" : nothing}
        stroke-linejoin="round" stroke-linecap="round"></path>`
    })}</g>`
  })

  const dots = series.map((s) => {
    if (s.spec.kind === "bar") return nothing
    return svg`
      ${s.spec.dots ? s.points.map((p) => (p ? svg`<circle class="dot" cx=${p.x} cy=${p.y} r="3" stroke=${s.color} stroke-width=${Math.max(1, s.spec.strokeWidth)}></circle>` : nothing)) : nothing}
      ${tooltip && active >= 0 && s.points[active] ? svg`<circle class="active-dot" cx=${s.points[active]!.x} cy=${s.points[active]!.y} r="4" fill=${s.color}></circle>` : nothing}
    `
  })

  return svg`
    <defs>${gradients}</defs>
    ${gridLines}
    ${cursor}
    ${areas}
    ${bars}
    ${lines}
    ${dots}
    ${renderAxes(model, ctx)}
  `
}

function tickText(axis: TecChartAxis, value: unknown, index: number): string {
  if (axis.tickFormatter) return String(axis.tickFormatter(value, index))
  return value == null ? "" : String(value)
}

function renderAxes(model: CartesianModel, ctx: ChartContext): SVGTemplateResult {
  const { plot, horizontal, slots } = model
  const key = categoryKeyOf(ctx)
  const categories = ctx.rows.map((row, i) => (key ? row?.[key] : i))
  const xAxis = xAxisOf(ctx)
  const yAxis = yAxisOf(ctx)
  const out: SVGTemplateResult[] = []
  const fontSize = ctx.fontSize

  if (xAxis) {
    const y = plot.y + plot.h
    const items = horizontal
      ? model.valueTicks.map((t, i) => ({ coordinate: t.pos, text: tickText(xAxis, t.value, i) }))
      : slots.map((s, i) => ({ coordinate: s.center, text: tickText(xAxis, categories[i], i) }))
    // Labels may extend into the chart's margins (the first and last category sit at the edges of
    // the plot), and are only thinned or nudged where they would leave the chart.
    const shown = thinTicks(
      items.map((t) => t.coordinate),
      (i) => ctx.measure(items[i]!.text),
      0,
      ctx.width,
      xAxis.minTickGap
    )
    const ty = y + TICK_SIZE + xAxis.tickMargin
    out.push(svg`<g class="x-axis">
      ${xAxis.axisLine ? svg`<line class="axis-line" x1=${plot.x} x2=${plot.x + plot.w} y1=${y} y2=${y}></line>` : nothing}
      ${shown.map(
        (t) => svg`
          ${xAxis.tickLine ? svg`<line class="tick-line" x1=${t.coordinate} x2=${t.coordinate} y1=${y} y2=${y + TICK_SIZE}></line>` : nothing}
          <text class="tick" x=${t.labelCoordinate} y=${ty} dy="0.71em" text-anchor="middle">${items[t.index]!.text}</text>`
      )}
    </g>`)
  }

  if (yAxis) {
    const x = plot.x
    const items = horizontal
      ? slots.map((s, i) => ({ coordinate: s.center, text: tickText(yAxis, categories[i], i) }))
      : model.valueTicks.map((t, i) => ({ coordinate: t.pos, text: tickText(yAxis, t.value, i) }))
    // Keep labels from overlapping (walk from the bottom for values, from the top for categories).
    let limit = horizontal ? -Infinity : Infinity
    const visible = items.filter((t) => {
      const ok = horizontal ? t.coordinate - fontSize / 2 >= limit : t.coordinate + fontSize / 2 <= limit
      if (ok) limit = horizontal ? t.coordinate + fontSize / 2 + yAxis.minTickGap : t.coordinate - fontSize / 2 - yAxis.minTickGap
      return ok
    })
    const tx = x - TICK_SIZE - yAxis.tickMargin
    out.push(svg`<g class="y-axis">
      ${yAxis.axisLine ? svg`<line class="axis-line" x1=${x} x2=${x} y1=${plot.y} y2=${plot.y + plot.h}></line>` : nothing}
      ${visible.map(
        (t) => svg`
          ${yAxis.tickLine ? svg`<line class="tick-line" x1=${x - TICK_SIZE} x2=${x} y1=${t.coordinate} y2=${t.coordinate}></line>` : nothing}
          <text class="tick" x=${tx} y=${t.coordinate} dy="0.355em" text-anchor="end">${t.text}</text>`
      )}
    </g>`)
  }
  return svg`${out}`
}

/** The category's name as text: the tooltip's formatted label when it is text, else the config label or raw value. */
export function categoryText(ctx: ChartContext, index: number): string {
  const key = categoryKeyOf(ctx)
  const raw = key ? ctx.rows[index]?.[key] : index + 1
  const tooltip = ctx.tooltip
  if (tooltip?.labelFormatter && key) {
    const value = typeof raw === "string" ? (ctx.config[raw]?.label ?? raw) : raw
    const formatted = tooltip.labelFormatter(value, [])
    if (typeof formatted === "string") return formatted
  }
  return ctx.text(raw)
}

export const cartesianKind: ChartKind<CartesianModel> = {
  id: "cartesian",
  mirrored: true,
  claims: () => true,
  label(ctx) {
    const kind = seriesSpecs(ctx)[0]?.kind ?? ctx.host.type
    return kind ? `${kind[0]!.toUpperCase()}${kind.slice(1)} chart` : "Chart"
  },
  model: computeModel,
  render: renderCartesian,
  payload(model, index, ctx) {
    const row = ctx.rows[index]
    if (!row) return { label: undefined, items: [] }
    const key = categoryKeyOf(ctx)
    return {
      label: key ? row[key] : index,
      items: model.series.map((s) => ({ dataKey: s.spec.key, name: s.spec.key, value: row[s.spec.key], color: s.color, row })),
    }
  },
  anchor(model, index) {
    const slot = model.slots[index]
    if (!slot) return undefined
    return model.horizontal ? { x: model.plot.x + model.plot.w / 2, y: slot.center } : { x: slot.center, y: model.plot.y + model.plot.h / 2 }
  },
  hit(model, point) {
    const { plot } = model
    if (point.x < plot.x || point.x > plot.x + plot.w || point.y < plot.y || point.y > plot.y + plot.h) return -1
    return categoryAt(model.slots, model.horizontal ? point.y : point.x)
  },
  table(model, ctx) {
    const specs = model.specs
    if (!specs.length || !ctx.rows.length) return nothing
    const key = categoryKeyOf(ctx)
    const config = ctx.config
    return html`<table part="table" class="sr-only">
      <caption>${ctx.name()}</caption>
      <thead>
        <tr>
          <th scope="col">${key ? (config[key]?.label ?? key) : "#"}</th>
          ${specs.map((s) => html`<th scope="col">${config[s.key]?.label ?? s.key}</th>`)}
        </tr>
      </thead>
      <tbody>
        ${ctx.rows.map(
          (row, i) => html`<tr>
            <th scope="row">${categoryText(ctx, i)}</th>
            ${specs.map((s) => html`<td>${formatValue(row?.[s.key], ctx.locale)}</td>`)}
          </tr>`
        )}
      </tbody>
    </table>`
  },
  legend(model) {
    return model.series.map((s) => ({ dataKey: s.spec.key, color: s.color }))
  },
}
